"""create tbl_weblinks

Revision ID: 0388d2b81d29
Revises: 3c73ec525105
Create Date: 2025-04-01 10:22:44.790699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0388d2b81d29'
down_revision: Union[str, None] = '3c73ec525105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_web_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('weblink', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_web_links_created_by'), 'tbl_web_links', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_web_links_id'), 'tbl_web_links', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_web_links_name'), 'tbl_web_links', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_web_links_updated_by'), 'tbl_web_links', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tbl_web_links_weblink'), 'tbl_web_links', ['weblink'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_web_links_weblink'), table_name='tbl_web_links')
    op.drop_index(op.f('ix_tbl_web_links_updated_by'), table_name='tbl_web_links')
    op.drop_index(op.f('ix_tbl_web_links_name'), table_name='tbl_web_links')
    op.drop_index(op.f('ix_tbl_web_links_id'), table_name='tbl_web_links')
    op.drop_index(op.f('ix_tbl_web_links_created_by'), table_name='tbl_web_links')
    op.drop_table('tbl_web_links')
    # ### end Alembic commands ###
