"""changed mobile number and whatsapp number to string

Revision ID: 18e13513d919
Revises: 45bf691a7736
Create Date: 2025-06-12 12:15:26.510730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e13513d919'
down_revision: Union[str, None] = '45bf691a7736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_user', 'mobile_no',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('tbl_user', 'mobile_country_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=True)
    op.alter_column('tbl_user', 'whatsapp_no',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('tbl_user', 'whatsapp_country_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=True)
    
    op.alter_column('tbl_confreres', 'mobile_no',
               existing_type=sa.String(length=32),
               type_=sa.String(length=32),
               existing_nullable=False,
               postgresql_using='mobile_no::text')
    op.alter_column('tbl_confreres', 'country_code',
               existing_type=sa.String(length=8),
               type_=sa.String(length=8),
               existing_nullable=False,
               postgresql_using='country_code::text')
    # ### end Alembic commands ###


def downgrade() -> None: pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('tbl_user', 'whatsapp_country_code',
    #            existing_type=sa.String(length=8),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    # op.alter_column('tbl_user', 'whatsapp_no',
    #            existing_type=sa.String(length=32),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('tbl_user', 'mobile_country_code',
    #            existing_type=sa.String(length=8),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    # op.alter_column('tbl_user', 'mobile_no',
    #            existing_type=sa.String(length=32),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('tbl_confreres', 'country_code',
    #            existing_type=sa.String(length=8),
    #            type_=sa.INTEGER(),
    #            existing_nullable=False)
    # op.alter_column('tbl_confreres', 'mobile_no',
    #            existing_type=sa.String(length=32),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
