"""financial_map

Revision ID: 1e8943a92826
Revises: f6e1d1ee011a
Create Date: 2025-03-17 15:26:17.056625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8943a92826'
down_revision: Union[str, None] = 'f6e1d1ee011a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_portfolio_financial_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('non_financial_portfolio_id', sa.Integer(), nullable=False),
    sa.Column('financial_portfolio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_portfolio_id'], ['tbl_portfolio.id'], ),
    sa.ForeignKeyConstraint(['non_financial_portfolio_id'], ['tbl_portfolio.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_portfolio_financial_map_created_by'), 'tbl_portfolio_financial_map', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_portfolio_financial_map_financial_portfolio_id'), 'tbl_portfolio_financial_map', ['financial_portfolio_id'], unique=False)
    op.create_index(op.f('ix_tbl_portfolio_financial_map_id'), 'tbl_portfolio_financial_map', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_portfolio_financial_map_non_financial_portfolio_id'), 'tbl_portfolio_financial_map', ['non_financial_portfolio_id'], unique=False)
    op.create_index(op.f('ix_tbl_portfolio_financial_map_updated_by'), 'tbl_portfolio_financial_map', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_portfolio_financial_map_updated_by'), table_name='tbl_portfolio_financial_map')
    op.drop_index(op.f('ix_tbl_portfolio_financial_map_non_financial_portfolio_id'), table_name='tbl_portfolio_financial_map')
    op.drop_index(op.f('ix_tbl_portfolio_financial_map_id'), table_name='tbl_portfolio_financial_map')
    op.drop_index(op.f('ix_tbl_portfolio_financial_map_financial_portfolio_id'), table_name='tbl_portfolio_financial_map')
    op.drop_index(op.f('ix_tbl_portfolio_financial_map_created_by'), table_name='tbl_portfolio_financial_map')
    op.drop_table('tbl_portfolio_financial_map')
    # ### end Alembic commands ###
