"""community_user_role

Revision ID: 1f3d1defbc54
Revises: 1e8943a92826
Create Date: 2025-03-18 12:35:03.720148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3d1defbc54'
down_revision: Union[str, None] = '1e8943a92826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_user_CFP_map', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tbl_user_CFP_map_role_id'), 'tbl_user_CFP_map', ['role_id'], unique=False)
    op.create_foreign_key('tbl_user_CFP_map_role_id_fkey', 'tbl_user_CFP_map', 'tbl_role', ['role_id'], ['id'], ondelete='CASCADE')
    op.add_column('tbl_user_community_map', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tbl_user_community_map_role_id'), 'tbl_user_community_map', ['role_id'], unique=False)
    op.create_foreign_key('tbl_user_community_map_role_id_fkey', 'tbl_user_community_map', 'tbl_role', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_user_community_map_role_id_fkey', 'tbl_user_community_map', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_user_community_map_role_id'), table_name='tbl_user_community_map')
    op.drop_column('tbl_user_community_map', 'role_id')
    op.drop_constraint('tbl_user_CFP_map_role_id_fkey', 'tbl_user_CFP_map', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_user_CFP_map_role_id'), table_name='tbl_user_CFP_map')
    op.drop_column('tbl_user_CFP_map', 'role_id')
    # ### end Alembic commands ###
