"""Added Diocese Table

Revision ID: 2b52ea031611
Revises: d7279b12aa25
Create Date: 2025-03-20 14:59:44.409192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b52ea031611'
down_revision: Union[str, None] = 'd7279b12aa25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_diocese',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('place', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['tbl_country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['tbl_district.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['tbl_province.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['tbl_region.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['tbl_state.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_diocese_address'), 'tbl_diocese', ['address'], unique=False)
    op.create_index(op.f('ix_tbl_diocese_code'), 'tbl_diocese', ['code'], unique=False)
    op.create_index(op.f('ix_tbl_diocese_country_id'), 'tbl_diocese', ['country_id'], unique=False)
    op.create_index(op.f('ix_tbl_diocese_created_by'), 'tbl_diocese', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_diocese_district_id'), 'tbl_diocese', ['district_id'], unique=False)
    op.create_index(op.f('ix_tbl_diocese_id'), 'tbl_diocese', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_diocese_name'), 'tbl_diocese', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_diocese_place'), 'tbl_diocese', ['place'], unique=False)
    op.create_index(op.f('ix_tbl_diocese_province_id'), 'tbl_diocese', ['province_id'], unique=False)
    op.create_index(op.f('ix_tbl_diocese_region_id'), 'tbl_diocese', ['region_id'], unique=False)
    op.create_index(op.f('ix_tbl_diocese_state_id'), 'tbl_diocese', ['state_id'], unique=False)
    op.create_index(op.f('ix_tbl_diocese_updated_by'), 'tbl_diocese', ['updated_by'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_diocese_updated_by'), table_name='tbl_diocese')
    op.drop_index(op.f('ix_tbl_diocese_state_id'), table_name='tbl_diocese')
    op.drop_index(op.f('ix_tbl_diocese_region_id'), table_name='tbl_diocese')
    op.drop_index(op.f('ix_tbl_diocese_province_id'), table_name='tbl_diocese')
    op.drop_index(op.f('ix_tbl_diocese_place'), table_name='tbl_diocese')
    op.drop_index(op.f('ix_tbl_diocese_name'), table_name='tbl_diocese')
    op.drop_index(op.f('ix_tbl_diocese_id'), table_name='tbl_diocese')
    op.drop_index(op.f('ix_tbl_diocese_district_id'), table_name='tbl_diocese')
    op.drop_index(op.f('ix_tbl_diocese_created_by'), table_name='tbl_diocese')
    op.drop_index(op.f('ix_tbl_diocese_country_id'), table_name='tbl_diocese')
    op.drop_index(op.f('ix_tbl_diocese_code'), table_name='tbl_diocese')
    op.drop_index(op.f('ix_tbl_diocese_address'), table_name='tbl_diocese')
    op.drop_table('tbl_diocese')
    # ### end Alembic commands ###
