"""community_answer

Revision ID: 3c73ec525105
Revises: 68bbbe6ce564
Create Date: 2025-03-31 18:45:45.713406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c73ec525105'
down_revision: Union[str, None] = '68bbbe6ce564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_community_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['community_id'], ['tbl_community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_year'], ['tbl_financial_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_community_answer_category_id'), 'tbl_community_answer', ['category_id'], unique=False)
    op.create_index(op.f('ix_tbl_community_answer_community_id'), 'tbl_community_answer', ['community_id'], unique=False)
    op.create_index(op.f('ix_tbl_community_answer_created_by'), 'tbl_community_answer', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_community_answer_financial_year'), 'tbl_community_answer', ['financial_year'], unique=False)
    op.create_index(op.f('ix_tbl_community_answer_id'), 'tbl_community_answer', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_community_answer_updated_by'), 'tbl_community_answer', ['updated_by'], unique=False)
    op.create_table('tbl_community_answer_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('community_answer_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('answer_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_answer_id'], ['tbl_community_answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_answer_data_gin', 'tbl_community_answer_data', ['answer_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tbl_community_answer_data_community_answer_id'), 'tbl_community_answer_data', ['community_answer_id'], unique=False)
    op.create_index(op.f('ix_tbl_community_answer_data_created_by'), 'tbl_community_answer_data', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_community_answer_data_id'), 'tbl_community_answer_data', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_community_answer_data_updated_by'), 'tbl_community_answer_data', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_community_answer_data_updated_by'), table_name='tbl_community_answer_data')
    op.drop_index(op.f('ix_tbl_community_answer_data_id'), table_name='tbl_community_answer_data')
    op.drop_index(op.f('ix_tbl_community_answer_data_created_by'), table_name='tbl_community_answer_data')
    op.drop_index(op.f('ix_tbl_community_answer_data_community_answer_id'), table_name='tbl_community_answer_data')
    op.drop_index('idx_answer_data_gin', table_name='tbl_community_answer_data', postgresql_using='gin')
    op.drop_table('tbl_community_answer_data')
    op.drop_index(op.f('ix_tbl_community_answer_updated_by'), table_name='tbl_community_answer')
    op.drop_index(op.f('ix_tbl_community_answer_id'), table_name='tbl_community_answer')
    op.drop_index(op.f('ix_tbl_community_answer_financial_year'), table_name='tbl_community_answer')
    op.drop_index(op.f('ix_tbl_community_answer_created_by'), table_name='tbl_community_answer')
    op.drop_index(op.f('ix_tbl_community_answer_community_id'), table_name='tbl_community_answer')
    op.drop_index(op.f('ix_tbl_community_answer_category_id'), table_name='tbl_community_answer')
    op.drop_table('tbl_community_answer')
    # ### end Alembic commands ###
