"""added state id in district field

Revision ID: 45bf691a7736
Revises: 5e0ee0302d7c
Create Date: 2025-06-02 14:54:36.166164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bf691a7736'
down_revision: Union[str, None] = '5e0ee0302d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_district', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tbl_district_state_id'), 'tbl_district', ['state_id'], unique=False)
    op.create_foreign_key('tbl_district_state_id_fkey', 'tbl_district', 'tbl_state', ['state_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_district_state_id_fkey', 'tbl_district', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_district_state_id'), table_name='tbl_district')
    op.drop_column('tbl_district', 'state_id')
    # ### end Alembic commands ###
