"""province id added in communication

Revision ID: 4d35e203f6e1
Revises: ba75b949c52f
Create Date: 2025-04-22 10:03:01.957037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d35e203f6e1'
down_revision: Union[str, None] = 'ba75b949c52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_communication', sa.Column('province_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tbl_communication_province_id'), 'tbl_communication', ['province_id'], unique=False)
    op.create_foreign_key('tbl_communication_province_id_fkey', 'tbl_communication', 'tbl_province', ['province_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_communication_province_id_fkey', 'tbl_communication', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_communication_province_id'), table_name='tbl_communication')
    op.drop_column('tbl_communication', 'province_id')
    # ### end Alembic commands ###
