"""answer_finyear

Revision ID: 4f082a5e1bdd
Revises: 4d35e203f6e1
Create Date: 2025-04-29 11:35:50.868703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f082a5e1bdd'
down_revision: Union[str, None] = '4d35e203f6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tbl_answer_financial_year', table_name='tbl_answer')
    op.drop_constraint('tbl_answer_financial_year_fkey', 'tbl_answer', type_='foreignkey')
    op.drop_column('tbl_answer', 'financial_year')
    op.add_column('tbl_answer_data', sa.Column('financial_year', sa.Integer(), nullable=False))
    op.add_column('tbl_answer_data', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('tbl_answer_data', sa.Column('end_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_tbl_answer_data_financial_year'), 'tbl_answer_data', ['financial_year'], unique=False)
    op.create_index(op.f('ix_tbl_answer_data_end_date'), 'tbl_answer_data', ['end_date'], unique=False)
    op.create_index(op.f('ix_tbl_answer_data_start_date'), 'tbl_answer_data', ['start_date'], unique=False)
    op.create_foreign_key('fk_tbl_answer_data_tbl_financial_year', 'tbl_answer_data', 'tbl_financial_year', ['financial_year'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tbl_answer_data_tbl_financial_year', 'tbl_answer_data', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_answer_data_financial_year'), table_name='tbl_answer_data')
    op.drop_index(op.f('ix_tbl_answer_data_start_date'), table_name='tbl_answer_data')
    op.drop_index(op.f('ix_tbl_answer_data_end_date'), table_name='tbl_answer_data')
    op.drop_column('tbl_answer_data', 'financial_year')
    op.drop_column('tbl_answer_data', 'end_date')
    op.drop_column('tbl_answer_data', 'start_date')
    op.add_column('tbl_answer', sa.Column('financial_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tbl_answer_financial_year_fkey', 'tbl_answer', 'tbl_financial_year', ['financial_year'], ['id'], ondelete='CASCADE')
    op.create_index('ix_tbl_answer_financial_year', 'tbl_answer', ['financial_year'], unique=False)
    # ### end Alembic commands ###
