"""access_control_tbl

Revision ID: 59974dd3c72c
Revises: 
Create Date: 2025-03-17 11:08:04.035041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59974dd3c72c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_country_id'), 'tbl_country', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_country_name'), 'tbl_country', ['name'], unique=False)
    op.create_table('tbl_feature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_feature_id'), 'tbl_feature', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_feature_name'), 'tbl_feature', ['name'], unique=False)
    op.create_table('tbl_module',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_module_id'), 'tbl_module', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_module_name'), 'tbl_module', ['name'], unique=False)
    # op.create_index(op.f('ix_tbl_module_type'), 'tbl_module', ['type'], unique=False)
    op.create_table('tbl_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_role_id'), 'tbl_role', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_role_name'), 'tbl_role', ['name'], unique=False)
    op.create_table('tbl_module_feature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['tbl_feature.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['tbl_module.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_module_feature_feature_id'), 'tbl_module_feature', ['feature_id'], unique=False)
    op.create_index(op.f('ix_tbl_module_feature_id'), 'tbl_module_feature', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_module_feature_module_id'), 'tbl_module_feature', ['module_id'], unique=False)
    op.create_table('tbl_role_module_feature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['tbl_feature.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['tbl_module.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_role_module_feature_feature_id'), 'tbl_role_module_feature', ['feature_id'], unique=False)
    op.create_index(op.f('ix_tbl_role_module_feature_id'), 'tbl_role_module_feature', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_role_module_feature_module_id'), 'tbl_role_module_feature', ['module_id'], unique=False)
    op.create_index(op.f('ix_tbl_role_module_feature_role_id'), 'tbl_role_module_feature', ['role_id'], unique=False)
    op.create_table('tbl_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['tbl_country.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_state_country_id'), 'tbl_state', ['country_id'], unique=False)
    op.create_index(op.f('ix_tbl_state_id'), 'tbl_state', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_state_name'), 'tbl_state', ['name'], unique=False)
    op.create_table('tbl_region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['tbl_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_region_id'), 'tbl_region', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_region_name'), 'tbl_region', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_region_state_id'), 'tbl_region', ['state_id'], unique=False)
    op.create_table('tbl_district',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['tbl_region.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_district_id'), 'tbl_district', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_district_name'), 'tbl_district', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_district_region_id'), 'tbl_district', ['region_id'], unique=False)
    op.create_table('tbl_province',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('place', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('country_ids', sa.String(length=150), nullable=True),
    sa.Column('state_ids', sa.String(length=150), nullable=True),
    sa.Column('region_ids', sa.String(length=150), nullable=True),
    sa.Column('district_ids', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['tbl_country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['district_id'], ['tbl_district.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['tbl_region.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['tbl_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_province_address'), 'tbl_province', ['address'], unique=False)
    op.create_index(op.f('ix_tbl_province_code'), 'tbl_province', ['code'], unique=False)
    op.create_index(op.f('ix_tbl_province_country_id'), 'tbl_province', ['country_id'], unique=False)
    op.create_index(op.f('ix_tbl_province_district_id'), 'tbl_province', ['district_id'], unique=False)
    op.create_index(op.f('ix_tbl_province_id'), 'tbl_province', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_province_name'), 'tbl_province', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_province_place'), 'tbl_province', ['place'], unique=False)
    op.create_index(op.f('ix_tbl_province_region_id'), 'tbl_province', ['region_id'], unique=False)
    op.create_index(op.f('ix_tbl_province_state_id'), 'tbl_province', ['state_id'], unique=False)
    op.create_table('tbl_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('mobile_no', sa.BigInteger(), nullable=True),
    sa.Column('mobile_country_code', sa.Integer(), nullable=True),
    sa.Column('whatsapp_no', sa.BigInteger(), nullable=True),
    sa.Column('whatsapp_country_code', sa.Integer(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=250), nullable=True),
    sa.Column('profile_pic', sa.String(length=250), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('forgot_pin', sa.Integer(), nullable=True),
    sa.Column('pin_expiration', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['tbl_province.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_email'), 'tbl_user', ['email'], unique=False)
    op.create_index(op.f('ix_tbl_user_gender'), 'tbl_user', ['gender'], unique=False)
    op.create_index(op.f('ix_tbl_user_id'), 'tbl_user', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_mobile_no'), 'tbl_user', ['mobile_no'], unique=False)
    op.create_index(op.f('ix_tbl_user_name'), 'tbl_user', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_user_province_id'), 'tbl_user', ['province_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_role_id'), 'tbl_user', ['role_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_username'), 'tbl_user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_user_username'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_role_id'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_province_id'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_name'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_mobile_no'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_id'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_gender'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_email'), table_name='tbl_user')
    op.drop_table('tbl_user')
    op.drop_index(op.f('ix_tbl_province_state_id'), table_name='tbl_province')
    op.drop_index(op.f('ix_tbl_province_region_id'), table_name='tbl_province')
    op.drop_index(op.f('ix_tbl_province_place'), table_name='tbl_province')
    op.drop_index(op.f('ix_tbl_province_name'), table_name='tbl_province')
    op.drop_index(op.f('ix_tbl_province_id'), table_name='tbl_province')
    op.drop_index(op.f('ix_tbl_province_district_id'), table_name='tbl_province')
    op.drop_index(op.f('ix_tbl_province_country_id'), table_name='tbl_province')
    op.drop_index(op.f('ix_tbl_province_code'), table_name='tbl_province')
    op.drop_index(op.f('ix_tbl_province_address'), table_name='tbl_province')
    op.drop_table('tbl_province')
    op.drop_index(op.f('ix_tbl_district_region_id'), table_name='tbl_district')
    op.drop_index(op.f('ix_tbl_district_name'), table_name='tbl_district')
    op.drop_index(op.f('ix_tbl_district_id'), table_name='tbl_district')
    op.drop_table('tbl_district')
    op.drop_index(op.f('ix_tbl_region_state_id'), table_name='tbl_region')
    op.drop_index(op.f('ix_tbl_region_name'), table_name='tbl_region')
    op.drop_index(op.f('ix_tbl_region_id'), table_name='tbl_region')
    op.drop_table('tbl_region')
    op.drop_index(op.f('ix_tbl_state_name'), table_name='tbl_state')
    op.drop_index(op.f('ix_tbl_state_id'), table_name='tbl_state')
    op.drop_index(op.f('ix_tbl_state_country_id'), table_name='tbl_state')
    op.drop_table('tbl_state')
    op.drop_index(op.f('ix_tbl_role_module_feature_role_id'), table_name='tbl_role_module_feature')
    op.drop_index(op.f('ix_tbl_role_module_feature_module_id'), table_name='tbl_role_module_feature')
    op.drop_index(op.f('ix_tbl_role_module_feature_id'), table_name='tbl_role_module_feature')
    op.drop_index(op.f('ix_tbl_role_module_feature_feature_id'), table_name='tbl_role_module_feature')
    op.drop_table('tbl_role_module_feature')
    op.drop_index(op.f('ix_tbl_module_feature_module_id'), table_name='tbl_module_feature')
    op.drop_index(op.f('ix_tbl_module_feature_id'), table_name='tbl_module_feature')
    op.drop_index(op.f('ix_tbl_module_feature_feature_id'), table_name='tbl_module_feature')
    op.drop_table('tbl_module_feature')
    op.drop_index(op.f('ix_tbl_role_name'), table_name='tbl_role')
    op.drop_index(op.f('ix_tbl_role_id'), table_name='tbl_role')
    op.drop_table('tbl_role')
    # op.drop_index(op.f('ix_tbl_module_type'), table_name='tbl_module')
    op.drop_index(op.f('ix_tbl_module_name'), table_name='tbl_module')
    op.drop_index(op.f('ix_tbl_module_id'), table_name='tbl_module')
    op.drop_table('tbl_module')
    op.drop_index(op.f('ix_tbl_feature_name'), table_name='tbl_feature')
    op.drop_index(op.f('ix_tbl_feature_id'), table_name='tbl_feature')
    op.drop_table('tbl_feature')
    op.drop_index(op.f('ix_tbl_country_name'), table_name='tbl_country')
    op.drop_index(op.f('ix_tbl_country_id'), table_name='tbl_country')
    op.drop_table('tbl_country')
    # ### end Alembic commands ###
