"""audit log province id & record title null true added

Revision ID: 5e0ee0302d7c
Revises: c19e1826c6ad
Create Date: 2025-05-21 11:51:46.014311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0ee0302d7c'
down_revision: Union[str, None] = 'c19e1826c6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_audit_log', 'province_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tbl_audit_log', 'record_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_audit_log', 'record_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tbl_audit_log', 'province_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
