"""category_financial_due

Revision ID: 68bbbe6ce564
Revises: a58373f239b6
Create Date: 2025-03-26 17:29:32.629348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68bbbe6ce564'
down_revision: Union[str, None] = 'a58373f239b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_category_financial_year_due_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('due_month', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['tbl_financial_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_category_financial_year_due_map_category_id'), 'tbl_category_financial_year_due_map', ['category_id'], unique=False)
    op.create_index(op.f('ix_tbl_category_financial_year_due_map_created_by'), 'tbl_category_financial_year_due_map', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_category_financial_year_due_map_financial_year_id'), 'tbl_category_financial_year_due_map', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_tbl_category_financial_year_due_map_id'), 'tbl_category_financial_year_due_map', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_category_financial_year_due_map_updated_by'), 'tbl_category_financial_year_due_map', ['updated_by'], unique=False)
    op.drop_column('tbl_category', 'due_month')
    op.drop_column('tbl_category', 'due_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_category', sa.Column('due_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tbl_category', sa.Column('due_month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tbl_category_financial_year_due_map_updated_by'), table_name='tbl_category_financial_year_due_map')
    op.drop_index(op.f('ix_tbl_category_financial_year_due_map_id'), table_name='tbl_category_financial_year_due_map')
    op.drop_index(op.f('ix_tbl_category_financial_year_due_map_financial_year_id'), table_name='tbl_category_financial_year_due_map')
    op.drop_index(op.f('ix_tbl_category_financial_year_due_map_created_by'), table_name='tbl_category_financial_year_due_map')
    op.drop_index(op.f('ix_tbl_category_financial_year_due_map_category_id'), table_name='tbl_category_financial_year_due_map')
    op.drop_table('tbl_category_financial_year_due_map')
    # ### end Alembic commands ###
