"""addes type in financial portfolios

Revision ID: 86dfadc465e1
Revises: 18e13513d919
Create Date: 2025-06-13 16:48:54.514103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86dfadc465e1'
down_revision: Union[str, None] = '18e13513d919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_CFP', sa.Column('type', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tbl_CFP_type'), 'tbl_CFP', ['type'], unique=False)
    op.add_column('tbl_LEFP', sa.Column('type', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tbl_LEFP_type'), 'tbl_LEFP', ['type'], unique=False)
    op.add_column('tbl_SFP', sa.Column('type', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tbl_SFP_type'), 'tbl_SFP', ['type'], unique=False)
    op.alter_column('tbl_confreres', 'country_code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_confreres', 'country_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_index(op.f('ix_tbl_SFP_type'), table_name='tbl_SFP')
    op.drop_column('tbl_SFP', 'type')
    op.drop_index(op.f('ix_tbl_LEFP_type'), table_name='tbl_LEFP')
    op.drop_column('tbl_LEFP', 'type')
    op.drop_index(op.f('ix_tbl_CFP_type'), table_name='tbl_CFP')
    op.drop_column('tbl_CFP', 'type')
    # ### end Alembic commands ###
