"""alter answer table

Revision ID: 88c6867bd067
Revises: b2195c6cf68c
Create Date: 2025-04-04 12:25:20.941420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88c6867bd067'
down_revision: Union[str, None] = 'b2195c6cf68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_answer_data_gin', table_name='tbl_community_answer_data', postgresql_using='gin')
    op.drop_index('ix_tbl_community_answer_data_community_answer_id', table_name='tbl_community_answer_data')
    op.drop_index('ix_tbl_community_answer_data_created_by', table_name='tbl_community_answer_data')
    op.drop_index('ix_tbl_community_answer_data_id', table_name='tbl_community_answer_data')
    op.drop_index('ix_tbl_community_answer_data_updated_by', table_name='tbl_community_answer_data')
    op.drop_table('tbl_community_answer_data')
    op.drop_index('ix_tbl_community_answer_category_id', table_name='tbl_community_answer')
    op.drop_index('ix_tbl_community_answer_community_id', table_name='tbl_community_answer')
    op.drop_index('ix_tbl_community_answer_created_by', table_name='tbl_community_answer')
    op.drop_index('ix_tbl_community_answer_financial_year', table_name='tbl_community_answer')
    op.drop_index('ix_tbl_community_answer_id', table_name='tbl_community_answer')
    op.drop_index('ix_tbl_community_answer_updated_by', table_name='tbl_community_answer')
    op.drop_table('tbl_community_answer')

    op.drop_index('idx_society_answer_data_gin', table_name='tbl_society_answer_data', postgresql_using='gin')
    op.drop_index('ix_tbl_society_answer_data_created_by', table_name='tbl_society_answer_data')
    op.drop_index('ix_tbl_society_answer_data_id', table_name='tbl_society_answer_data')
    op.drop_index('ix_tbl_society_answer_data_society_answer_id', table_name='tbl_society_answer_data')
    op.drop_index('ix_tbl_society_answer_data_updated_by', table_name='tbl_society_answer_data')
    op.drop_table('tbl_society_answer_data')
    op.drop_index('ix_tbl_society_answer_category_id', table_name='tbl_society_answer')
    op.drop_index('ix_tbl_society_answer_created_by', table_name='tbl_society_answer')
    op.drop_index('ix_tbl_society_answer_financial_year', table_name='tbl_society_answer')
    op.drop_index('ix_tbl_society_answer_id', table_name='tbl_society_answer')
    op.drop_index('ix_tbl_society_answer_society_id', table_name='tbl_society_answer')
    op.drop_index('ix_tbl_society_answer_updated_by', table_name='tbl_society_answer')
    op.drop_table('tbl_society_answer')

    op.drop_index('idx_legal_entity_answer_data_gin', table_name='tbl_legal_entity_answer_data', postgresql_using='gin')
    op.drop_index('ix_tbl_legal_entity_answer_data_created_by', table_name='tbl_legal_entity_answer_data')
    op.drop_index('ix_tbl_legal_entity_answer_data_id', table_name='tbl_legal_entity_answer_data')
    op.drop_index('ix_tbl_legal_entity_answer_data_legal_entity_answer_id', table_name='tbl_legal_entity_answer_data')
    op.drop_index('ix_tbl_legal_entity_answer_data_updated_by', table_name='tbl_legal_entity_answer_data')
    op.drop_table('tbl_legal_entity_answer_data')
    op.drop_index('ix_tbl_legal_entity_answer_category_id', table_name='tbl_legal_entity_answer')
    op.drop_index('ix_tbl_legal_entity_answer_created_by', table_name='tbl_legal_entity_answer')
    op.drop_index('ix_tbl_legal_entity_answer_financial_year', table_name='tbl_legal_entity_answer')
    op.drop_index('ix_tbl_legal_entity_answer_id', table_name='tbl_legal_entity_answer')
    op.drop_index('ix_tbl_legal_entity_answer_legal_entity_id', table_name='tbl_legal_entity_answer')
    op.drop_index('ix_tbl_legal_entity_answer_updated_by', table_name='tbl_legal_entity_answer')
    op.drop_table('tbl_legal_entity_answer')

    
    # update new table
    op.create_table('tbl_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('cfp_id', sa.Integer(), nullable=True),
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('sfp_id', sa.Integer(), nullable=True),
    sa.Column('legal_entity_id', sa.Integer(), nullable=True),
    sa.Column('lefp_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cfp_id'], ['tbl_CFP.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['community_id'], ['tbl_community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_year'], ['tbl_financial_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lefp_id'], ['tbl_LEFP.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['tbl_legal_entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sfp_id'], ['tbl_SFP.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['tbl_society.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_answer_category_id'), 'tbl_answer', ['category_id'], unique=False)
    op.create_index(op.f('ix_tbl_answer_cfp_id'), 'tbl_answer', ['cfp_id'], unique=False)
    op.create_index(op.f('ix_tbl_answer_community_id'), 'tbl_answer', ['community_id'], unique=False)
    op.create_index(op.f('ix_tbl_answer_created_by'), 'tbl_answer', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_answer_financial_year'), 'tbl_answer', ['financial_year'], unique=False)
    op.create_index(op.f('ix_tbl_answer_id'), 'tbl_answer', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_answer_lefp_id'), 'tbl_answer', ['lefp_id'], unique=False)
    op.create_index(op.f('ix_tbl_answer_legal_entity_id'), 'tbl_answer', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_tbl_answer_sfp_id'), 'tbl_answer', ['sfp_id'], unique=False)
    op.create_index(op.f('ix_tbl_answer_society_id'), 'tbl_answer', ['society_id'], unique=False)
    op.create_index(op.f('ix_tbl_answer_updated_by'), 'tbl_answer', ['updated_by'], unique=False)
    op.create_table('tbl_answer_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('answer_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['tbl_answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_answer_data_gin', 'tbl_answer_data', ['answer_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tbl_answer_data_answer_id'), 'tbl_answer_data', ['answer_id'], unique=False)
    op.create_index(op.f('ix_tbl_answer_data_created_by'), 'tbl_answer_data', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_answer_data_id'), 'tbl_answer_data', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_answer_data_updated_by'), 'tbl_answer_data', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # drop tables answer
    op.drop_index(op.f('ix_tbl_answer_data_updated_by'), table_name='tbl_answer_data')
    op.drop_index(op.f('ix_tbl_answer_data_id'), table_name='tbl_answer_data')
    op.drop_index(op.f('ix_tbl_answer_data_created_by'), table_name='tbl_answer_data')
    op.drop_index(op.f('ix_tbl_answer_data_answer_id'), table_name='tbl_answer_data')
    op.drop_index('idx_answer_data_gin', table_name='tbl_answer_data', postgresql_using='gin')
    op.drop_table('tbl_answer_data')
    op.drop_index(op.f('ix_tbl_answer_updated_by'), table_name='tbl_answer')
    op.drop_index(op.f('ix_tbl_answer_society_id'), table_name='tbl_answer')
    op.drop_index(op.f('ix_tbl_answer_sfp_id'), table_name='tbl_answer')
    op.drop_index(op.f('ix_tbl_answer_legal_entity_id'), table_name='tbl_answer')
    op.drop_index(op.f('ix_tbl_answer_lefp_id'), table_name='tbl_answer')
    op.drop_index(op.f('ix_tbl_answer_id'), table_name='tbl_answer')
    op.drop_index(op.f('ix_tbl_answer_financial_year'), table_name='tbl_answer')
    op.drop_index(op.f('ix_tbl_answer_created_by'), table_name='tbl_answer')
    op.drop_index(op.f('ix_tbl_answer_community_id'), table_name='tbl_answer')
    op.drop_index(op.f('ix_tbl_answer_cfp_id'), table_name='tbl_answer')
    op.drop_index(op.f('ix_tbl_answer_category_id'), table_name='tbl_answer')
    op.drop_table('tbl_answer')

    op.create_table('tbl_community_answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], name='tbl_community_answer_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['community_id'], ['tbl_community.id'], name='tbl_community_answer_community_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], name='tbl_community_answer_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_year'], ['tbl_financial_year.id'], name='tbl_community_answer_financial_year_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], name='tbl_community_answer_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tbl_community_answer_pkey')
    )
    op.create_index('ix_tbl_community_answer_updated_by', 'tbl_community_answer', ['updated_by'], unique=False)
    op.create_index('ix_tbl_community_answer_id', 'tbl_community_answer', ['id'], unique=False)
    op.create_index('ix_tbl_community_answer_financial_year', 'tbl_community_answer', ['financial_year'], unique=False)
    op.create_index('ix_tbl_community_answer_created_by', 'tbl_community_answer', ['created_by'], unique=False)
    op.create_index('ix_tbl_community_answer_community_id', 'tbl_community_answer', ['community_id'], unique=False)
    op.create_index('ix_tbl_community_answer_category_id', 'tbl_community_answer', ['category_id'], unique=False)
    op.create_table('tbl_community_answer_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('community_answer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['community_answer_id'], ['tbl_community_answer.id'], name='tbl_community_answer_data_community_answer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], name='tbl_community_answer_data_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], name='tbl_community_answer_data_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tbl_community_answer_data_pkey')
    )
    op.create_index('ix_tbl_community_answer_data_updated_by', 'tbl_community_answer_data', ['updated_by'], unique=False)
    op.create_index('ix_tbl_community_answer_data_id', 'tbl_community_answer_data', ['id'], unique=False)
    op.create_index('ix_tbl_community_answer_data_created_by', 'tbl_community_answer_data', ['created_by'], unique=False)
    op.create_index('ix_tbl_community_answer_data_community_answer_id', 'tbl_community_answer_data', ['community_answer_id'], unique=False)
    op.create_index('idx_answer_data_gin', 'tbl_community_answer_data', ['answer_data'], unique=False, postgresql_using='gin')
    
    op.create_table('tbl_society_answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('society_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], name='tbl_society_answer_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], name='tbl_society_answer_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_year'], ['tbl_financial_year.id'], name='tbl_society_answer_financial_year_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['tbl_society.id'], name='tbl_society_answer_society_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], name='tbl_society_answer_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tbl_society_answer_pkey')
    )
    op.create_index('ix_tbl_society_answer_updated_by', 'tbl_society_answer', ['updated_by'], unique=False)
    op.create_index('ix_tbl_society_answer_society_id', 'tbl_society_answer', ['society_id'], unique=False)
    op.create_index('ix_tbl_society_answer_id', 'tbl_society_answer', ['id'], unique=False)
    op.create_index('ix_tbl_society_answer_financial_year', 'tbl_society_answer', ['financial_year'], unique=False)
    op.create_index('ix_tbl_society_answer_created_by', 'tbl_society_answer', ['created_by'], unique=False)
    op.create_index('ix_tbl_society_answer_category_id', 'tbl_society_answer', ['category_id'], unique=False)
    op.create_table('tbl_society_answer_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('society_answer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], name='tbl_society_answer_data_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['society_answer_id'], ['tbl_society_answer.id'], name='tbl_society_answer_data_society_answer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], name='tbl_society_answer_data_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tbl_society_answer_data_pkey')
    )
    op.create_index('ix_tbl_society_answer_data_updated_by', 'tbl_society_answer_data', ['updated_by'], unique=False)
    op.create_index('ix_tbl_society_answer_data_society_answer_id', 'tbl_society_answer_data', ['society_answer_id'], unique=False)
    op.create_index('ix_tbl_society_answer_data_id', 'tbl_society_answer_data', ['id'], unique=False)
    op.create_index('ix_tbl_society_answer_data_created_by', 'tbl_society_answer_data', ['created_by'], unique=False)
    op.create_index('idx_society_answer_data_gin', 'tbl_society_answer_data', ['answer_data'], unique=False, postgresql_using='gin')
    op.create_table('tbl_legal_entity_answer',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tbl_legal_entity_answer_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('legal_entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], name='tbl_legal_entity_answer_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], name='tbl_legal_entity_answer_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_year'], ['tbl_financial_year.id'], name='tbl_legal_entity_answer_financial_year_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['tbl_legal_entity.id'], name='tbl_legal_entity_answer_legal_entity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], name='tbl_legal_entity_answer_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tbl_legal_entity_answer_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_tbl_legal_entity_answer_updated_by', 'tbl_legal_entity_answer', ['updated_by'], unique=False)
    op.create_index('ix_tbl_legal_entity_answer_legal_entity_id', 'tbl_legal_entity_answer', ['legal_entity_id'], unique=False)
    op.create_index('ix_tbl_legal_entity_answer_id', 'tbl_legal_entity_answer', ['id'], unique=False)
    op.create_index('ix_tbl_legal_entity_answer_financial_year', 'tbl_legal_entity_answer', ['financial_year'], unique=False)
    op.create_index('ix_tbl_legal_entity_answer_created_by', 'tbl_legal_entity_answer', ['created_by'], unique=False)
    op.create_index('ix_tbl_legal_entity_answer_category_id', 'tbl_legal_entity_answer', ['category_id'], unique=False)
    op.create_table('tbl_legal_entity_answer_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('legal_entity_answer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], name='tbl_legal_entity_answer_data_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['legal_entity_answer_id'], ['tbl_legal_entity_answer.id'], name='tbl_legal_entity_answer_data_legal_entity_answer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], name='tbl_legal_entity_answer_data_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tbl_legal_entity_answer_data_pkey')
    )
    op.create_index('ix_tbl_legal_entity_answer_data_updated_by', 'tbl_legal_entity_answer_data', ['updated_by'], unique=False)
    op.create_index('ix_tbl_legal_entity_answer_data_legal_entity_answer_id', 'tbl_legal_entity_answer_data', ['legal_entity_answer_id'], unique=False)
    op.create_index('ix_tbl_legal_entity_answer_data_id', 'tbl_legal_entity_answer_data', ['id'], unique=False)
    op.create_index('ix_tbl_legal_entity_answer_data_created_by', 'tbl_legal_entity_answer_data', ['created_by'], unique=False)
    op.create_index('idx_legal_entity_answer_data_gin', 'tbl_legal_entity_answer_data', ['answer_data'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
