"""metadata, active & form table

Revision ID: a58373f239b6
Revises: cea17cc671f9
Create Date: 2025-03-26 15:52:54.363822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58373f239b6'
down_revision: Union[str, None] = 'cea17cc671f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_data_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_data_types_id'), 'tbl_data_types', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_data_types_name'), 'tbl_data_types', ['name'], unique=False)
    op.create_table('tbl_file_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_file_types_id'), 'tbl_file_types', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_file_types_name'), 'tbl_file_types', ['name'], unique=False)
    op.create_table('tbl_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('type', sa.String(length=250), nullable=False),
    sa.Column('is_renewal', sa.Boolean(), nullable=False),
    sa.Column('renewal_iteration', sa.Integer(), nullable=True),
    sa.Column('is_due', sa.Boolean(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('due_month', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_category_created_by'), 'tbl_category', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_category_id'), 'tbl_category', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_category_name'), 'tbl_category', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_category_type'), 'tbl_category', ['type'], unique=False)
    op.create_index(op.f('ix_tbl_category_updated_by'), 'tbl_category', ['updated_by'], unique=False)
    op.create_table('tbl_financial_year',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_financial_year_created_by'), 'tbl_financial_year', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_financial_year_id'), 'tbl_financial_year', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_financial_year_updated_by'), 'tbl_financial_year', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tbl_financial_year_year'), 'tbl_financial_year', ['year'], unique=False)
    op.create_table('tbl_category_form',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('data_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('placeholder', sa.String(length=250), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('regex', sa.String(length=250), nullable=True),
    sa.Column('regex_error_msg', sa.String(length=250), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('allow_decimal', sa.Boolean(), nullable=True),
    sa.Column('max_file_size', sa.Float(), nullable=True),
    sa.Column('allow_past_date', sa.Boolean(), nullable=True),
    sa.Column('allow_future_date', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['data_type_id'], ['tbl_data_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_category_form_category_id'), 'tbl_category_form', ['category_id'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_created_by'), 'tbl_category_form', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_data_type_id'), 'tbl_category_form', ['data_type_id'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_id'), 'tbl_category_form', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_name'), 'tbl_category_form', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_updated_by'), 'tbl_category_form', ['updated_by'], unique=False)
    op.create_table('tbl_portfolio_category_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['tbl_portfolio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_portfolio_category_map_category_id'), 'tbl_portfolio_category_map', ['category_id'], unique=False)
    op.create_index(op.f('ix_tbl_portfolio_category_map_created_by'), 'tbl_portfolio_category_map', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_portfolio_category_map_id'), 'tbl_portfolio_category_map', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_portfolio_category_map_portfolio_id'), 'tbl_portfolio_category_map', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_tbl_portfolio_category_map_updated_by'), 'tbl_portfolio_category_map', ['updated_by'], unique=False)
    op.create_table('tbl_category_form_file_type_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_form_id', sa.Integer(), nullable=False),
    sa.Column('file_type_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_form_id'], ['tbl_category_form.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_type_id'], ['tbl_file_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_category_form_file_type_map_category_form_id'), 'tbl_category_form_file_type_map', ['category_form_id'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_file_type_map_created_by'), 'tbl_category_form_file_type_map', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_file_type_map_file_type_id'), 'tbl_category_form_file_type_map', ['file_type_id'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_file_type_map_id'), 'tbl_category_form_file_type_map', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_file_type_map_updated_by'), 'tbl_category_form_file_type_map', ['updated_by'], unique=False)
    op.create_table('tbl_category_form_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_form_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=250), nullable=False),
    sa.Column('default_select', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_form_id'], ['tbl_category_form.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_category_form_options_category_form_id'), 'tbl_category_form_options', ['category_form_id'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_options_created_by'), 'tbl_category_form_options', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_options_id'), 'tbl_category_form_options', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_options_updated_by'), 'tbl_category_form_options', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tbl_category_form_options_value'), 'tbl_category_form_options', ['value'], unique=False)
    op.add_column('tbl_CFP', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_LEFP', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_SFP', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_community', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_country', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.create_index(op.f('ix_tbl_country_created_by'), 'tbl_country', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_country_updated_by'), 'tbl_country', ['updated_by'], unique=False)
    op.create_foreign_key('tbl_country_created_by_fkey', 'tbl_country', 'tbl_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tbl_country_updated_by_fkey', 'tbl_country', 'tbl_user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('tbl_diocese', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_district', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.create_index(op.f('ix_tbl_district_created_by'), 'tbl_district', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_district_updated_by'), 'tbl_district', ['updated_by'], unique=False)
    op.create_foreign_key('tbl_district_created_by_fkey', 'tbl_district', 'tbl_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tbl_district_updated_by_fkey', 'tbl_district', 'tbl_user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('tbl_feature', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.create_index(op.f('ix_tbl_feature_created_by'), 'tbl_feature', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_feature_updated_by'), 'tbl_feature', ['updated_by'], unique=False)
    op.create_foreign_key('tbl_feature_updated_by_fkey', 'tbl_feature', 'tbl_user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tbl_feature_created_by_fkey', 'tbl_feature', 'tbl_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('tbl_legal_entity', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_module', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    # op.drop_index('ix_tbl_module_type', table_name='tbl_module')
    op.create_index(op.f('ix_tbl_module_created_by'), 'tbl_module', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_module_updated_by'), 'tbl_module', ['updated_by'], unique=False)
    op.create_foreign_key('tbl_module_created_by_fkey', 'tbl_module', 'tbl_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tbl_module_updated_by_fkey', 'tbl_module', 'tbl_user', ['updated_by'], ['id'], ondelete='SET NULL')
    # op.drop_column('tbl_module', 'type')
    op.add_column('tbl_module_feature', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.create_index(op.f('ix_tbl_module_feature_created_by'), 'tbl_module_feature', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_module_feature_updated_by'), 'tbl_module_feature', ['updated_by'], unique=False)
    op.create_foreign_key('tbl_module_feature_updated_by_fkey', 'tbl_module_feature', 'tbl_user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tbl_module_feature_created_by_fkey', 'tbl_module_feature', 'tbl_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('tbl_portfolio', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_portfolio_financial_map', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_province', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.create_index(op.f('ix_tbl_province_created_by'), 'tbl_province', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_province_updated_by'), 'tbl_province', ['updated_by'], unique=False)
    op.create_foreign_key('tbl_province_created_by_fkey', 'tbl_province', 'tbl_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tbl_province_updated_by_fkey', 'tbl_province', 'tbl_user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('tbl_region', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.create_index(op.f('ix_tbl_region_created_by'), 'tbl_region', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_region_updated_by'), 'tbl_region', ['updated_by'], unique=False)
    op.create_foreign_key('tbl_region_updated_by_fkey', 'tbl_region', 'tbl_user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tbl_region_created_by_fkey', 'tbl_region', 'tbl_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('tbl_role', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.create_index(op.f('ix_tbl_role_created_by'), 'tbl_role', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_role_updated_by'), 'tbl_role', ['updated_by'], unique=False)
    op.create_foreign_key('tbl_role_created_by_fkey', 'tbl_role', 'tbl_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tbl_role_updated_by_fkey', 'tbl_role', 'tbl_user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('tbl_role_module_feature', sa.Column('module_feature_id', sa.Integer(), nullable=False))
    op.add_column('tbl_role_module_feature', sa.Column('status', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('tbl_role_module_feature', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.drop_index('ix_tbl_role_module_feature_feature_id', table_name='tbl_role_module_feature')
    op.drop_index('ix_tbl_role_module_feature_module_id', table_name='tbl_role_module_feature')
    op.create_index(op.f('ix_tbl_role_module_feature_created_by'), 'tbl_role_module_feature', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_role_module_feature_module_feature_id'), 'tbl_role_module_feature', ['module_feature_id'], unique=False)
    op.create_index(op.f('ix_tbl_role_module_feature_updated_by'), 'tbl_role_module_feature', ['updated_by'], unique=False)
    op.drop_constraint('tbl_role_module_feature_feature_id_fkey', 'tbl_role_module_feature', type_='foreignkey')
    op.drop_constraint('tbl_role_module_feature_module_id_fkey', 'tbl_role_module_feature', type_='foreignkey')
    op.create_foreign_key('tbl_role_module_feature_module_feature_id_fkey', 'tbl_role_module_feature', 'tbl_module_feature', ['module_feature_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tbl_role_module_feature_updated_by_fkey', 'tbl_role_module_feature', 'tbl_user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tbl_role_module_feature_created_by_fkey', 'tbl_role_module_feature', 'tbl_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('tbl_role_module_feature', 'module_id')
    op.drop_column('tbl_role_module_feature', 'feature_id')
    op.add_column('tbl_society', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_state', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.create_index(op.f('ix_tbl_state_created_by'), 'tbl_state', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_state_updated_by'), 'tbl_state', ['updated_by'], unique=False)
    op.create_foreign_key('tbl_state_created_by_fkey', 'tbl_state', 'tbl_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tbl_state_updated_by_fkey', 'tbl_state', 'tbl_user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('tbl_user', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_user_CFP_map', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_user_LEFP_map', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_user_SFP_map', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_user_community_map', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_user_legal_entity_map', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('tbl_user_society_map', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_user_society_map', 'active')
    op.drop_column('tbl_user_legal_entity_map', 'active')
    op.drop_column('tbl_user_community_map', 'active')
    op.drop_column('tbl_user_SFP_map', 'active')
    op.drop_column('tbl_user_LEFP_map', 'active')
    op.drop_column('tbl_user_CFP_map', 'active')
    op.drop_column('tbl_user', 'active')
    op.drop_constraint('tbl_state_updated_by_fkey', 'tbl_state', type_='foreignkey')
    op.drop_constraint('tbl_state_created_by_fkey', 'tbl_state', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_state_updated_by'), table_name='tbl_state')
    op.drop_index(op.f('ix_tbl_state_created_by'), table_name='tbl_state')
    op.drop_column('tbl_state', 'active')
    op.drop_column('tbl_society', 'active')
    op.add_column('tbl_role_module_feature', sa.Column('feature_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tbl_role_module_feature', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('tbl_role_module_feature_created_by_fkey', 'tbl_role_module_feature', type_='foreignkey')
    op.drop_constraint('tbl_role_module_feature_updated_by_fkey', 'tbl_role_module_feature', type_='foreignkey')
    op.drop_constraint('tbl_role_module_feature_module_feature_id_fkey', 'tbl_role_module_feature', type_='foreignkey')
    op.create_foreign_key('tbl_role_module_feature_module_id_fkey', 'tbl_role_module_feature', 'tbl_module', ['module_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tbl_role_module_feature_feature_id_fkey', 'tbl_role_module_feature', 'tbl_feature', ['feature_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tbl_role_module_feature_updated_by'), table_name='tbl_role_module_feature')
    op.drop_index(op.f('ix_tbl_role_module_feature_module_feature_id'), table_name='tbl_role_module_feature')
    op.drop_index(op.f('ix_tbl_role_module_feature_created_by'), table_name='tbl_role_module_feature')
    op.create_index('ix_tbl_role_module_feature_module_id', 'tbl_role_module_feature', ['module_id'], unique=False)
    op.create_index('ix_tbl_role_module_feature_feature_id', 'tbl_role_module_feature', ['feature_id'], unique=False)
    op.drop_column('tbl_role_module_feature', 'active')
    op.drop_column('tbl_role_module_feature', 'status')
    op.drop_column('tbl_role_module_feature', 'module_feature_id')
    op.drop_constraint('tbl_role_created_by_fkey', 'tbl_role', type_='foreignkey')
    op.drop_constraint('tbl_role_updated_by_fkey', 'tbl_role', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_role_updated_by'), table_name='tbl_role')
    op.drop_index(op.f('ix_tbl_role_created_by'), table_name='tbl_role')
    op.drop_column('tbl_role', 'active')
    op.drop_constraint('tbl_region_created_by_fkey', 'tbl_region', type_='foreignkey')
    op.drop_constraint('tbl_region_updated_by_fkey', 'tbl_region', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_region_updated_by'), table_name='tbl_region')
    op.drop_index(op.f('ix_tbl_region_created_by'), table_name='tbl_region')
    op.drop_column('tbl_region', 'active')
    op.drop_constraint('tbl_province_created_by_fkey', 'tbl_province', type_='foreignkey')
    op.drop_constraint('tbl_province_updated_by_fkey', 'tbl_province', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_province_updated_by'), table_name='tbl_province')
    op.drop_index(op.f('ix_tbl_province_created_by'), table_name='tbl_province')
    op.drop_column('tbl_province', 'active')
    op.drop_column('tbl_portfolio_financial_map', 'active')
    op.drop_column('tbl_portfolio', 'active')
    op.drop_constraint('tbl_module_feature_created_by_fkey', 'tbl_module_feature', type_='foreignkey')
    op.drop_constraint('tbl_module_feature_updated_by_fkey', 'tbl_module_feature', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_module_feature_updated_by'), table_name='tbl_module_feature')
    op.drop_index(op.f('ix_tbl_module_feature_created_by'), table_name='tbl_module_feature')
    op.drop_column('tbl_module_feature', 'active')
    # op.add_column('tbl_module', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint('tbl_module_created_by_fkey', 'tbl_module', type_='foreignkey')
    op.drop_constraint('tbl_module_updated_by_fkey', 'tbl_module', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_module_updated_by'), table_name='tbl_module')
    op.drop_index(op.f('ix_tbl_module_created_by'), table_name='tbl_module')
    # op.create_index('ix_tbl_module_type', 'tbl_module', ['type'], unique=False)
    op.drop_column('tbl_module', 'active')
    op.drop_column('tbl_legal_entity', 'active')
    op.drop_constraint('tbl_feature_created_by_fkey', 'tbl_feature', type_='foreignkey')
    op.drop_constraint('tbl_feature_updated_by_fkey', 'tbl_feature', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_feature_updated_by'), table_name='tbl_feature')
    op.drop_index(op.f('ix_tbl_feature_created_by'), table_name='tbl_feature')
    op.drop_column('tbl_feature', 'active')
    op.drop_constraint('tbl_district_created_by_fkey', 'tbl_district', type_='foreignkey')
    op.drop_constraint('tbl_district_updated_by_fkey', 'tbl_district', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_district_updated_by'), table_name='tbl_district')
    op.drop_index(op.f('ix_tbl_district_created_by'), table_name='tbl_district')
    op.drop_column('tbl_district', 'active')
    op.drop_column('tbl_diocese', 'active')
    op.drop_constraint('tbl_country_created_by_fkey', 'tbl_country', type_='foreignkey')
    op.drop_constraint('tbl_country_updated_by_fkey', 'tbl_country', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_country_updated_by'), table_name='tbl_country')
    op.drop_index(op.f('ix_tbl_country_created_by'), table_name='tbl_country')
    op.drop_column('tbl_country', 'active')
    op.drop_column('tbl_community', 'active')
    op.drop_column('tbl_SFP', 'active')
    op.drop_column('tbl_LEFP', 'active')
    op.drop_column('tbl_CFP', 'active')
    op.drop_index(op.f('ix_tbl_category_form_options_value'), table_name='tbl_category_form_options')
    op.drop_index(op.f('ix_tbl_category_form_options_updated_by'), table_name='tbl_category_form_options')
    op.drop_index(op.f('ix_tbl_category_form_options_id'), table_name='tbl_category_form_options')
    op.drop_index(op.f('ix_tbl_category_form_options_created_by'), table_name='tbl_category_form_options')
    op.drop_index(op.f('ix_tbl_category_form_options_category_form_id'), table_name='tbl_category_form_options')
    op.drop_table('tbl_category_form_options')
    op.drop_index(op.f('ix_tbl_category_form_file_type_map_updated_by'), table_name='tbl_category_form_file_type_map')
    op.drop_index(op.f('ix_tbl_category_form_file_type_map_id'), table_name='tbl_category_form_file_type_map')
    op.drop_index(op.f('ix_tbl_category_form_file_type_map_file_type_id'), table_name='tbl_category_form_file_type_map')
    op.drop_index(op.f('ix_tbl_category_form_file_type_map_created_by'), table_name='tbl_category_form_file_type_map')
    op.drop_index(op.f('ix_tbl_category_form_file_type_map_category_form_id'), table_name='tbl_category_form_file_type_map')
    op.drop_table('tbl_category_form_file_type_map')
    op.drop_index(op.f('ix_tbl_portfolio_category_map_updated_by'), table_name='tbl_portfolio_category_map')
    op.drop_index(op.f('ix_tbl_portfolio_category_map_portfolio_id'), table_name='tbl_portfolio_category_map')
    op.drop_index(op.f('ix_tbl_portfolio_category_map_id'), table_name='tbl_portfolio_category_map')
    op.drop_index(op.f('ix_tbl_portfolio_category_map_created_by'), table_name='tbl_portfolio_category_map')
    op.drop_index(op.f('ix_tbl_portfolio_category_map_category_id'), table_name='tbl_portfolio_category_map')
    op.drop_table('tbl_portfolio_category_map')
    op.drop_index(op.f('ix_tbl_category_form_updated_by'), table_name='tbl_category_form')
    op.drop_index(op.f('ix_tbl_category_form_name'), table_name='tbl_category_form')
    op.drop_index(op.f('ix_tbl_category_form_id'), table_name='tbl_category_form')
    op.drop_index(op.f('ix_tbl_category_form_data_type_id'), table_name='tbl_category_form')
    op.drop_index(op.f('ix_tbl_category_form_created_by'), table_name='tbl_category_form')
    op.drop_index(op.f('ix_tbl_category_form_category_id'), table_name='tbl_category_form')
    op.drop_table('tbl_category_form')
    op.drop_index(op.f('ix_tbl_financial_year_year'), table_name='tbl_financial_year')
    op.drop_index(op.f('ix_tbl_financial_year_updated_by'), table_name='tbl_financial_year')
    op.drop_index(op.f('ix_tbl_financial_year_id'), table_name='tbl_financial_year')
    op.drop_index(op.f('ix_tbl_financial_year_created_by'), table_name='tbl_financial_year')
    op.drop_table('tbl_financial_year')
    op.drop_index(op.f('ix_tbl_category_updated_by'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_type'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_name'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_id'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_created_by'), table_name='tbl_category')
    op.drop_table('tbl_category')
    op.drop_index(op.f('ix_tbl_file_types_name'), table_name='tbl_file_types')
    op.drop_index(op.f('ix_tbl_file_types_id'), table_name='tbl_file_types')
    op.drop_table('tbl_file_types')
    op.drop_index(op.f('ix_tbl_data_types_name'), table_name='tbl_data_types')
    op.drop_index(op.f('ix_tbl_data_types_id'), table_name='tbl_data_types')
    op.drop_table('tbl_data_types')
    # ### end Alembic commands ###
