"""society & entity answer & user resign

Revision ID: b2195c6cf68c
Revises: d3bfb9584aa1
Create Date: 2025-04-03 17:10:00.614341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2195c6cf68c'
down_revision: Union[str, None] = 'd3bfb9584aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_society_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_year'], ['tbl_financial_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['tbl_society.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_society_answer_category_id'), 'tbl_society_answer', ['category_id'], unique=False)
    op.create_index(op.f('ix_tbl_society_answer_created_by'), 'tbl_society_answer', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_society_answer_financial_year'), 'tbl_society_answer', ['financial_year'], unique=False)
    op.create_index(op.f('ix_tbl_society_answer_id'), 'tbl_society_answer', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_society_answer_society_id'), 'tbl_society_answer', ['society_id'], unique=False)
    op.create_index(op.f('ix_tbl_society_answer_updated_by'), 'tbl_society_answer', ['updated_by'], unique=False)
    op.create_table('tbl_legal_entity_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legal_entity_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_year'], ['tbl_financial_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['tbl_legal_entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_legal_entity_answer_category_id'), 'tbl_legal_entity_answer', ['category_id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_answer_created_by'), 'tbl_legal_entity_answer', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_answer_financial_year'), 'tbl_legal_entity_answer', ['financial_year'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_answer_id'), 'tbl_legal_entity_answer', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_answer_legal_entity_id'), 'tbl_legal_entity_answer', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_answer_updated_by'), 'tbl_legal_entity_answer', ['updated_by'], unique=False)
    op.create_table('tbl_society_answer_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('society_answer_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('answer_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['society_answer_id'], ['tbl_society_answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_society_answer_data_gin', 'tbl_society_answer_data', ['answer_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tbl_society_answer_data_created_by'), 'tbl_society_answer_data', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_society_answer_data_id'), 'tbl_society_answer_data', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_society_answer_data_society_answer_id'), 'tbl_society_answer_data', ['society_answer_id'], unique=False)
    op.create_index(op.f('ix_tbl_society_answer_data_updated_by'), 'tbl_society_answer_data', ['updated_by'], unique=False)
    op.create_table('tbl_legal_entity_answer_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legal_entity_answer_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('answer_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['legal_entity_answer_id'], ['tbl_legal_entity_answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_legal_entity_answer_data_gin', 'tbl_legal_entity_answer_data', ['answer_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tbl_legal_entity_answer_data_created_by'), 'tbl_legal_entity_answer_data', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_answer_data_id'), 'tbl_legal_entity_answer_data', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_answer_data_legal_entity_answer_id'), 'tbl_legal_entity_answer_data', ['legal_entity_answer_id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_answer_data_updated_by'), 'tbl_legal_entity_answer_data', ['updated_by'], unique=False)
    op.add_column('tbl_user', sa.Column('resign_reason', sa.String(length=100), nullable=True))
    op.add_column('tbl_user', sa.Column('resign', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_user', 'resign_reason')
    op.drop_column('tbl_user', 'resign')
    op.drop_index(op.f('ix_tbl_legal_entity_answer_data_updated_by'), table_name='tbl_legal_entity_answer_data')
    op.drop_index(op.f('ix_tbl_legal_entity_answer_data_legal_entity_answer_id'), table_name='tbl_legal_entity_answer_data')
    op.drop_index(op.f('ix_tbl_legal_entity_answer_data_id'), table_name='tbl_legal_entity_answer_data')
    op.drop_index(op.f('ix_tbl_legal_entity_answer_data_created_by'), table_name='tbl_legal_entity_answer_data')
    op.drop_index('idx_legal_entity_answer_data_gin', table_name='tbl_legal_entity_answer_data', postgresql_using='gin')
    op.drop_table('tbl_legal_entity_answer_data')
    op.drop_index(op.f('ix_tbl_society_answer_data_updated_by'), table_name='tbl_society_answer_data')
    op.drop_index(op.f('ix_tbl_society_answer_data_society_answer_id'), table_name='tbl_society_answer_data')
    op.drop_index(op.f('ix_tbl_society_answer_data_id'), table_name='tbl_society_answer_data')
    op.drop_index(op.f('ix_tbl_society_answer_data_created_by'), table_name='tbl_society_answer_data')
    op.drop_index('idx_society_answer_data_gin', table_name='tbl_society_answer_data', postgresql_using='gin')
    op.drop_table('tbl_society_answer_data')
    op.drop_index(op.f('ix_tbl_legal_entity_answer_updated_by'), table_name='tbl_legal_entity_answer')
    op.drop_index(op.f('ix_tbl_legal_entity_answer_legal_entity_id'), table_name='tbl_legal_entity_answer')
    op.drop_index(op.f('ix_tbl_legal_entity_answer_id'), table_name='tbl_legal_entity_answer')
    op.drop_index(op.f('ix_tbl_legal_entity_answer_financial_year'), table_name='tbl_legal_entity_answer')
    op.drop_index(op.f('ix_tbl_legal_entity_answer_created_by'), table_name='tbl_legal_entity_answer')
    op.drop_index(op.f('ix_tbl_legal_entity_answer_category_id'), table_name='tbl_legal_entity_answer')
    op.drop_table('tbl_legal_entity_answer')
    op.drop_index(op.f('ix_tbl_society_answer_updated_by'), table_name='tbl_society_answer')
    op.drop_index(op.f('ix_tbl_society_answer_society_id'), table_name='tbl_society_answer')
    op.drop_index(op.f('ix_tbl_society_answer_id'), table_name='tbl_society_answer')
    op.drop_index(op.f('ix_tbl_society_answer_financial_year'), table_name='tbl_society_answer')
    op.drop_index(op.f('ix_tbl_society_answer_created_by'), table_name='tbl_society_answer')
    op.drop_index(op.f('ix_tbl_society_answer_category_id'), table_name='tbl_society_answer')
    op.drop_table('tbl_society_answer')
    # ### end Alembic commands ###
