"""add province id- category

Revision ID: b4e4b4fd2efe
Revises: e6bcca31735f
Create Date: 2025-04-11 12:14:41.740521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e4b4fd2efe'
down_revision: Union[str, None] = 'e6bcca31735f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_category', sa.Column('province_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tbl_category_province_id'), 'tbl_category', ['province_id'], unique=False)
    op.create_foreign_key('tbl_category_province_id_fkey', 'tbl_category', 'tbl_province', ['province_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_category_province_id_fkey', 'tbl_category', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_category_province_id'), table_name='tbl_category')
    op.drop_column('tbl_category', 'province_id')
    # ### end Alembic commands ###
