"""communication

Revision ID: ba75b949c52f
Revises: b4e4b4fd2efe
Create Date: 2025-04-15 12:51:34.174340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba75b949c52f'
down_revision: Union[str, None] = 'b4e4b4fd2efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_communication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=250), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=150), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_user_id'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_communication_content'), 'tbl_communication', ['content'], unique=False)
    op.create_index(op.f('ix_tbl_communication_created_by'), 'tbl_communication', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_communication_from_user_id'), 'tbl_communication', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_tbl_communication_id'), 'tbl_communication', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_communication_status'), 'tbl_communication', ['status'], unique=False)
    op.create_index(op.f('ix_tbl_communication_subject'), 'tbl_communication', ['subject'], unique=False)
    op.create_index(op.f('ix_tbl_communication_type'), 'tbl_communication', ['type'], unique=False)
    op.create_index(op.f('ix_tbl_communication_updated_by'), 'tbl_communication', ['updated_by'], unique=False)
    op.create_table('tbl_communication_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_version', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=250), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['communication_id'], ['tbl_communication.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_communication_attachment_communication_id'), 'tbl_communication_attachment', ['communication_id'], unique=False)
    op.create_index(op.f('ix_tbl_communication_attachment_created_by'), 'tbl_communication_attachment', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_communication_attachment_file'), 'tbl_communication_attachment', ['file'], unique=False)
    op.create_index(op.f('ix_tbl_communication_attachment_file_size'), 'tbl_communication_attachment', ['file_size'], unique=False)
    op.create_index(op.f('ix_tbl_communication_attachment_file_type'), 'tbl_communication_attachment', ['file_type'], unique=False)
    op.create_index(op.f('ix_tbl_communication_attachment_file_version'), 'tbl_communication_attachment', ['file_version'], unique=False)
    op.create_index(op.f('ix_tbl_communication_attachment_filename'), 'tbl_communication_attachment', ['filename'], unique=False)
    op.create_index(op.f('ix_tbl_communication_attachment_id'), 'tbl_communication_attachment', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_communication_attachment_updated_by'), 'tbl_communication_attachment', ['updated_by'], unique=False)
    op.create_table('tbl_communicaton_to_users_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['communication_id'], ['tbl_communication.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['tbl_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_communicaton_to_users_map_communication_id'), 'tbl_communicaton_to_users_map', ['communication_id'], unique=False)
    op.create_index(op.f('ix_tbl_communicaton_to_users_map_created_by'), 'tbl_communicaton_to_users_map', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_communicaton_to_users_map_id'), 'tbl_communicaton_to_users_map', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_communicaton_to_users_map_to_user_id'), 'tbl_communicaton_to_users_map', ['to_user_id'], unique=False)
    op.create_index(op.f('ix_tbl_communicaton_to_users_map_updated_by'), 'tbl_communicaton_to_users_map', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_communicaton_to_users_map_updated_by'), table_name='tbl_communicaton_to_users_map')
    op.drop_index(op.f('ix_tbl_communicaton_to_users_map_to_user_id'), table_name='tbl_communicaton_to_users_map')
    op.drop_index(op.f('ix_tbl_communicaton_to_users_map_id'), table_name='tbl_communicaton_to_users_map')
    op.drop_index(op.f('ix_tbl_communicaton_to_users_map_created_by'), table_name='tbl_communicaton_to_users_map')
    op.drop_index(op.f('ix_tbl_communicaton_to_users_map_communication_id'), table_name='tbl_communicaton_to_users_map')
    op.drop_table('tbl_communicaton_to_users_map')
    op.drop_index(op.f('ix_tbl_communication_attachment_updated_by'), table_name='tbl_communication_attachment')
    op.drop_index(op.f('ix_tbl_communication_attachment_id'), table_name='tbl_communication_attachment')
    op.drop_index(op.f('ix_tbl_communication_attachment_filename'), table_name='tbl_communication_attachment')
    op.drop_index(op.f('ix_tbl_communication_attachment_file_version'), table_name='tbl_communication_attachment')
    op.drop_index(op.f('ix_tbl_communication_attachment_file_type'), table_name='tbl_communication_attachment')
    op.drop_index(op.f('ix_tbl_communication_attachment_file_size'), table_name='tbl_communication_attachment')
    op.drop_index(op.f('ix_tbl_communication_attachment_file'), table_name='tbl_communication_attachment')
    op.drop_index(op.f('ix_tbl_communication_attachment_created_by'), table_name='tbl_communication_attachment')
    op.drop_index(op.f('ix_tbl_communication_attachment_communication_id'), table_name='tbl_communication_attachment')
    op.drop_table('tbl_communication_attachment')
    op.drop_index(op.f('ix_tbl_communication_updated_by'), table_name='tbl_communication')
    op.drop_index(op.f('ix_tbl_communication_type'), table_name='tbl_communication')
    op.drop_index(op.f('ix_tbl_communication_subject'), table_name='tbl_communication')
    op.drop_index(op.f('ix_tbl_communication_status'), table_name='tbl_communication')
    op.drop_index(op.f('ix_tbl_communication_id'), table_name='tbl_communication')
    op.drop_index(op.f('ix_tbl_communication_from_user_id'), table_name='tbl_communication')
    op.drop_index(op.f('ix_tbl_communication_created_by'), table_name='tbl_communication')
    op.drop_index(op.f('ix_tbl_communication_content'), table_name='tbl_communication')
    op.drop_table('tbl_communication')
    # ### end Alembic commands ###
