"""audit log model added

Revision ID: c19e1826c6ad
Revises: 8a9387af25d4
Create Date: 2025-05-19 19:36:20.229713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c19e1826c6ad'
down_revision: Union[str, None] = '8a9387af25d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_audit_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('record_title', sa.String(), nullable=False),
    sa.Column('modification_type', sa.String(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['tbl_province.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], name='fk_tbl_audit_log_tbl_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_tbl_audit_log_log_id'), 'tbl_audit_log', ['log_id'], unique=False)
    op.create_index(op.f('ix_tbl_audit_log_modification_type'), 'tbl_audit_log', ['modification_type'], unique=False)
    op.create_index(op.f('ix_tbl_audit_log_module_name'), 'tbl_audit_log', ['module_name'], unique=False)
    op.create_index(op.f('ix_tbl_audit_log_new_value'), 'tbl_audit_log', ['new_value'], unique=False)
    op.create_index(op.f('ix_tbl_audit_log_old_value'), 'tbl_audit_log', ['old_value'], unique=False)
    op.create_index(op.f('ix_tbl_audit_log_province_id'), 'tbl_audit_log', ['province_id'], unique=False)
    op.create_index(op.f('ix_tbl_audit_log_record_id'), 'tbl_audit_log', ['record_id'], unique=False)
    op.create_index(op.f('ix_tbl_audit_log_record_title'), 'tbl_audit_log', ['record_title'], unique=False)
    op.create_index(op.f('ix_tbl_audit_log_user_id'), 'tbl_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_tbl_audit_log_user_name'), 'tbl_audit_log', ['user_name'], unique=False)
    op.alter_column('tbl_CFP', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tbl_notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tbl_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_tbl_notifications_id'), 'tbl_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_notifications_user_id'), 'tbl_notifications', ['user_id'], unique=False)
    op.alter_column('tbl_user_community_map', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_user_community_map', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_tbl_notifications_user_id'), table_name='tbl_notifications')
    op.drop_index(op.f('ix_tbl_notifications_id'), table_name='tbl_notifications')
    op.alter_column('tbl_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tbl_notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tbl_CFP', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_tbl_audit_log_user_name'), table_name='tbl_audit_log')
    op.drop_index(op.f('ix_tbl_audit_log_user_id'), table_name='tbl_audit_log')
    op.drop_index(op.f('ix_tbl_audit_log_record_title'), table_name='tbl_audit_log')
    op.drop_index(op.f('ix_tbl_audit_log_record_id'), table_name='tbl_audit_log')
    op.drop_index(op.f('ix_tbl_audit_log_province_id'), table_name='tbl_audit_log')
    op.drop_index(op.f('ix_tbl_audit_log_old_value'), table_name='tbl_audit_log')
    op.drop_index(op.f('ix_tbl_audit_log_new_value'), table_name='tbl_audit_log')
    op.drop_index(op.f('ix_tbl_audit_log_module_name'), table_name='tbl_audit_log')
    op.drop_index(op.f('ix_tbl_audit_log_modification_type'), table_name='tbl_audit_log')
    op.drop_index(op.f('ix_tbl_audit_log_log_id'), table_name='tbl_audit_log')
    op.drop_table('tbl_audit_log')
    # ### end Alembic commands ###
