"""Added Confreres Table

Revision ID: c6aa0e876fb4
Revises: 88c6867bd067
Create Date: 2025-04-09 11:06:11.547626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6aa0e876fb4'
down_revision: Union[str, None] = '88c6867bd067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_confreres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('mobile_no', sa.BigInteger(), nullable=False),
    sa.Column('country_code', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_confreres_code'), 'tbl_confreres', ['code'], unique=False)
    op.create_index(op.f('ix_tbl_confreres_country_code'), 'tbl_confreres', ['country_code'], unique=False)
    op.create_index(op.f('ix_tbl_confreres_created_by'), 'tbl_confreres', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_confreres_email'), 'tbl_confreres', ['email'], unique=False)
    op.create_index(op.f('ix_tbl_confreres_id'), 'tbl_confreres', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_confreres_mobile_no'), 'tbl_confreres', ['mobile_no'], unique=False)
    op.create_index(op.f('ix_tbl_confreres_name'), 'tbl_confreres', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_confreres_updated_by'), 'tbl_confreres', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_confreres_updated_by'), table_name='tbl_confreres')
    op.drop_index(op.f('ix_tbl_confreres_name'), table_name='tbl_confreres')
    op.drop_index(op.f('ix_tbl_confreres_mobile_no'), table_name='tbl_confreres')
    op.drop_index(op.f('ix_tbl_confreres_id'), table_name='tbl_confreres')
    op.drop_index(op.f('ix_tbl_confreres_email'), table_name='tbl_confreres')
    op.drop_index(op.f('ix_tbl_confreres_created_by'), table_name='tbl_confreres')
    op.drop_index(op.f('ix_tbl_confreres_country_code'), table_name='tbl_confreres')
    op.drop_index(op.f('ix_tbl_confreres_code'), table_name='tbl_confreres')
    op.drop_table('tbl_confreres')
    # ### end Alembic commands ###
