"""update diocese

Revision ID: cea17cc671f9
Revises: b92892b24da8
Create Date: 2025-03-22 12:36:40.757984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea17cc671f9'
down_revision: Union[str, None] = 'b92892b24da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_legal_entity', sa.Column('diocese_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tbl_legal_entity_diocese_id'), 'tbl_legal_entity', ['diocese_id'], unique=False)
    op.create_foreign_key('fk_tbl_legal_entity_tbl_diocese', 'tbl_legal_entity', 'tbl_diocese', ['diocese_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tbl_legal_entity_tbl_diocese', 'tbl_legal_entity', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_legal_entity_diocese_id'), table_name='tbl_legal_entity')
    op.drop_column('tbl_legal_entity', 'diocese_id')
    # ### end Alembic commands ###
