"""add key for file type

Revision ID: d3bfb9584aa1
Revises: 0388d2b81d29
Create Date: 2025-04-01 17:07:02.401036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bfb9584aa1'
down_revision: Union[str, None] = '0388d2b81d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_file_types', sa.Column('data_type_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tbl_file_types_data_type_id'), 'tbl_file_types', ['data_type_id'], unique=False)
    op.create_foreign_key('tbl_file_types_data_type_id_fkey', 'tbl_file_types', 'tbl_data_types', ['data_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_file_types_data_type_id_fkey', 'tbl_file_types', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_file_types_data_type_id'), table_name='tbl_file_types')
    op.drop_column('tbl_file_types', 'data_type_id')
    # ### end Alembic commands ###
