"""SFP & LEFP user role

Revision ID: d7279b12aa25
Revises: 1f3d1defbc54
Create Date: 2025-03-19 11:03:30.220130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7279b12aa25'
down_revision: Union[str, None] = '1f3d1defbc54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_user_LEFP_map', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tbl_user_LEFP_map_role_id'), 'tbl_user_LEFP_map', ['role_id'], unique=False)
    op.create_foreign_key('tbl_user_LEFP_map_role_id_fkey', 'tbl_user_LEFP_map', 'tbl_role', ['role_id'], ['id'], ondelete='CASCADE')
    op.add_column('tbl_user_SFP_map', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tbl_user_SFP_map_role_id'), 'tbl_user_SFP_map', ['role_id'], unique=False)
    op.create_foreign_key('tbl_user_SFP_map_role_id_fkey', 'tbl_user_SFP_map', 'tbl_role', ['role_id'], ['id'], ondelete='CASCADE')
    op.add_column('tbl_user_legal_entity_map', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tbl_user_legal_entity_map_role_id'), 'tbl_user_legal_entity_map', ['role_id'], unique=False)
    op.create_foreign_key('tbl_user_legal_entity_map_role_id_fkey', 'tbl_user_legal_entity_map', 'tbl_role', ['role_id'], ['id'], ondelete='CASCADE')
    op.add_column('tbl_user_society_map', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tbl_user_society_map_role_id'), 'tbl_user_society_map', ['role_id'], unique=False)
    op.create_foreign_key('tbl_user_society_map_role_id_fkey', 'tbl_user_society_map', 'tbl_role', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_user_society_map_role_id_fkey', 'tbl_user_society_map', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_user_society_map_role_id'), table_name='tbl_user_society_map')
    op.drop_column('tbl_user_society_map', 'role_id')
    op.drop_constraint('tbl_user_legal_entity_map_role_id_fkey', 'tbl_user_legal_entity_map', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_user_legal_entity_map_role_id'), table_name='tbl_user_legal_entity_map')
    op.drop_column('tbl_user_legal_entity_map', 'role_id')
    op.drop_constraint('tbl_user_SFP_map_role_id_fkey', 'tbl_user_SFP_map', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_user_SFP_map_role_id'), table_name='tbl_user_SFP_map')
    op.drop_column('tbl_user_SFP_map', 'role_id')
    op.drop_constraint('tbl_user_LEFP_map_role_id_fkey', 'tbl_user_LEFP_map', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_user_LEFP_map_role_id'), table_name='tbl_user_LEFP_map')
    op.drop_column('tbl_user_LEFP_map', 'role_id')
    # ### end Alembic commands ###
