"""form validation date, time

Revision ID: e21aebdfdc4c
Revises: c6aa0e876fb4
Create Date: 2025-04-09 15:44:17.200065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21aebdfdc4c'
down_revision: Union[str, None] = 'c6aa0e876fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_category_form', sa.Column('time_format_24', sa.Boolean(), nullable=True))
    op.add_column('tbl_category_form', sa.Column('date_format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_category_form', 'date_format')
    op.drop_column('tbl_category_form', 'time_format_24')
    # ### end Alembic commands ###
