"""add provinceID in weblink & confreres

Revision ID: e6bcca31735f
Revises: e21aebdfdc4c
Create Date: 2025-04-10 14:41:51.409751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bcca31735f'
down_revision: Union[str, None] = 'e21aebdfdc4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_confreres', sa.Column('province_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tbl_confreres_province_id'), 'tbl_confreres', ['province_id'], unique=False)
    op.create_foreign_key('fk_tbl_confreres_tbl_province', 'tbl_confreres', 'tbl_province', ['province_id'], ['id'], ondelete='CASCADE')
    op.add_column('tbl_web_links', sa.Column('province_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tbl_web_links_province_id'), 'tbl_web_links', ['province_id'], unique=False)
    op.create_foreign_key("fk_tbl_web_links_tbl_province", 'tbl_web_links', 'tbl_province', ['province_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tbl_web_links_tbl_province', 'tbl_web_links', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_web_links_province_id'), table_name='tbl_web_links')
    op.drop_column('tbl_web_links', 'province_id')
    op.drop_constraint('fk_tbl_confreres_tbl_province', 'tbl_confreres', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_confreres_province_id'), table_name='tbl_confreres')
    op.drop_column('tbl_confreres', 'province_id')
    # ### end Alembic commands ###
