"""portfolio_master_table

Revision ID: f6e1d1ee011a
Revises: 59974dd3c72c
Create Date: 2025-03-17 12:15:43.790186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e1d1ee011a'
down_revision: Union[str, None] = '59974dd3c72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_community',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('acme_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('place', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['tbl_country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['tbl_district.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['tbl_province.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['tbl_region.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['tbl_state.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_community_acme_code'), 'tbl_community', ['acme_code'], unique=False)
    op.create_index(op.f('ix_tbl_community_address'), 'tbl_community', ['address'], unique=False)
    op.create_index(op.f('ix_tbl_community_code'), 'tbl_community', ['code'], unique=False)
    op.create_index(op.f('ix_tbl_community_country_id'), 'tbl_community', ['country_id'], unique=False)
    op.create_index(op.f('ix_tbl_community_created_by'), 'tbl_community', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_community_district_id'), 'tbl_community', ['district_id'], unique=False)
    op.create_index(op.f('ix_tbl_community_id'), 'tbl_community', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_community_name'), 'tbl_community', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_community_place'), 'tbl_community', ['place'], unique=False)
    op.create_index(op.f('ix_tbl_community_province_id'), 'tbl_community', ['province_id'], unique=False)
    op.create_index(op.f('ix_tbl_community_region_id'), 'tbl_community', ['region_id'], unique=False)
    op.create_index(op.f('ix_tbl_community_state_id'), 'tbl_community', ['state_id'], unique=False)
    op.create_index(op.f('ix_tbl_community_updated_by'), 'tbl_community', ['updated_by'], unique=False)
    op.create_table('tbl_portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_portfolio_created_by'), 'tbl_portfolio', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_portfolio_id'), 'tbl_portfolio', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_portfolio_name'), 'tbl_portfolio', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_portfolio_updated_by'), 'tbl_portfolio', ['updated_by'], unique=False)
    op.create_table('tbl_CFP',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('number', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['tbl_community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['tbl_portfolio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_CFP_community_id'), 'tbl_CFP', ['community_id'], unique=False)
    op.create_index(op.f('ix_tbl_CFP_created_by'), 'tbl_CFP', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_CFP_id'), 'tbl_CFP', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_CFP_number'), 'tbl_CFP', ['number'], unique=False)
    op.create_index(op.f('ix_tbl_CFP_portfolio_id'), 'tbl_CFP', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_tbl_CFP_updated_by'), 'tbl_CFP', ['updated_by'], unique=False)
    op.create_table('tbl_society',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('place', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['tbl_community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_id'], ['tbl_country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['tbl_district.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['tbl_province.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['tbl_region.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['tbl_state.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_society_address'), 'tbl_society', ['address'], unique=False)
    op.create_index(op.f('ix_tbl_society_code'), 'tbl_society', ['code'], unique=False)
    op.create_index(op.f('ix_tbl_society_community_id'), 'tbl_society', ['community_id'], unique=False)
    op.create_index(op.f('ix_tbl_society_country_id'), 'tbl_society', ['country_id'], unique=False)
    op.create_index(op.f('ix_tbl_society_created_by'), 'tbl_society', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_society_district_id'), 'tbl_society', ['district_id'], unique=False)
    op.create_index(op.f('ix_tbl_society_id'), 'tbl_society', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_society_name'), 'tbl_society', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_society_place'), 'tbl_society', ['place'], unique=False)
    op.create_index(op.f('ix_tbl_society_province_id'), 'tbl_society', ['province_id'], unique=False)
    op.create_index(op.f('ix_tbl_society_region_id'), 'tbl_society', ['region_id'], unique=False)
    op.create_index(op.f('ix_tbl_society_state_id'), 'tbl_society', ['state_id'], unique=False)
    op.create_index(op.f('ix_tbl_society_updated_by'), 'tbl_society', ['updated_by'], unique=False)
    op.create_table('tbl_user_community_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['tbl_community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_community_map_community_id'), 'tbl_user_community_map', ['community_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_community_map_created_by'), 'tbl_user_community_map', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_community_map_id'), 'tbl_user_community_map', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_community_map_updated_by'), 'tbl_user_community_map', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_community_map_user_id'), 'tbl_user_community_map', ['user_id'], unique=False)
    op.create_table('tbl_SFP',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('number', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['tbl_portfolio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['tbl_society.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_SFP_created_by'), 'tbl_SFP', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_SFP_id'), 'tbl_SFP', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_SFP_number'), 'tbl_SFP', ['number'], unique=False)
    op.create_index(op.f('ix_tbl_SFP_portfolio_id'), 'tbl_SFP', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_tbl_SFP_society_id'), 'tbl_SFP', ['society_id'], unique=False)
    op.create_index(op.f('ix_tbl_SFP_updated_by'), 'tbl_SFP', ['updated_by'], unique=False)
    op.create_table('tbl_legal_entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=150), nullable=True),
    sa.Column('financial_assistance', sa.String(length=100), nullable=True),
    sa.Column('board', sa.String(length=100), nullable=True),
    sa.Column('affiliation', sa.String(length=100), nullable=True),
    sa.Column('faculty', sa.String(length=100), nullable=True),
    sa.Column('ug_pg', sa.String(length=10), nullable=True),
    sa.Column('school_board', sa.String(length=100), nullable=True),
    sa.Column('medium_of_instruction', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('place', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['tbl_community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_id'], ['tbl_country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['tbl_district.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['tbl_portfolio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['tbl_province.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['tbl_region.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['tbl_society.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['tbl_state.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_legal_entity_address'), 'tbl_legal_entity', ['address'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_code'), 'tbl_legal_entity', ['code'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_community_id'), 'tbl_legal_entity', ['community_id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_country_id'), 'tbl_legal_entity', ['country_id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_created_by'), 'tbl_legal_entity', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_district_id'), 'tbl_legal_entity', ['district_id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_financial_assistance'), 'tbl_legal_entity', ['financial_assistance'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_id'), 'tbl_legal_entity', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_name'), 'tbl_legal_entity', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_place'), 'tbl_legal_entity', ['place'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_portfolio_id'), 'tbl_legal_entity', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_province_id'), 'tbl_legal_entity', ['province_id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_region_id'), 'tbl_legal_entity', ['region_id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_society_id'), 'tbl_legal_entity', ['society_id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_state_id'), 'tbl_legal_entity', ['state_id'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_type'), 'tbl_legal_entity', ['type'], unique=False)
    op.create_index(op.f('ix_tbl_legal_entity_updated_by'), 'tbl_legal_entity', ['updated_by'], unique=False)
    op.create_table('tbl_user_CFP_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cfp_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cfp_id'], ['tbl_CFP.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_CFP_map_cfp_id'), 'tbl_user_CFP_map', ['cfp_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_CFP_map_created_by'), 'tbl_user_CFP_map', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_CFP_map_id'), 'tbl_user_CFP_map', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_CFP_map_updated_by'), 'tbl_user_CFP_map', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_CFP_map_user_id'), 'tbl_user_CFP_map', ['user_id'], unique=False)
    op.create_table('tbl_user_society_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['society_id'], ['tbl_society.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_society_map_created_by'), 'tbl_user_society_map', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_society_map_id'), 'tbl_user_society_map', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_society_map_society_id'), 'tbl_user_society_map', ['society_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_society_map_updated_by'), 'tbl_user_society_map', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_society_map_user_id'), 'tbl_user_society_map', ['user_id'], unique=False)
    op.create_table('tbl_LEFP',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('legal_entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('number', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['tbl_legal_entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['tbl_portfolio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_LEFP_created_by'), 'tbl_LEFP', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_LEFP_id'), 'tbl_LEFP', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_LEFP_legal_entity_id'), 'tbl_LEFP', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_tbl_LEFP_number'), 'tbl_LEFP', ['number'], unique=False)
    op.create_index(op.f('ix_tbl_LEFP_portfolio_id'), 'tbl_LEFP', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_tbl_LEFP_updated_by'), 'tbl_LEFP', ['updated_by'], unique=False)
    op.create_table('tbl_user_SFP_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sfp_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sfp_id'], ['tbl_SFP.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_SFP_map_created_by'), 'tbl_user_SFP_map', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_SFP_map_id'), 'tbl_user_SFP_map', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_SFP_map_sfp_id'), 'tbl_user_SFP_map', ['sfp_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_SFP_map_updated_by'), 'tbl_user_SFP_map', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_SFP_map_user_id'), 'tbl_user_SFP_map', ['user_id'], unique=False)
    op.create_table('tbl_user_legal_entity_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('legal_entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['tbl_legal_entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_legal_entity_map_created_by'), 'tbl_user_legal_entity_map', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_legal_entity_map_id'), 'tbl_user_legal_entity_map', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_legal_entity_map_legal_entity_id'), 'tbl_user_legal_entity_map', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_legal_entity_map_updated_by'), 'tbl_user_legal_entity_map', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_legal_entity_map_user_id'), 'tbl_user_legal_entity_map', ['user_id'], unique=False)
    op.create_table('tbl_user_LEFP_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lefp_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lefp_id'], ['tbl_LEFP.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_LEFP_map_created_by'), 'tbl_user_LEFP_map', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_LEFP_map_id'), 'tbl_user_LEFP_map', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_LEFP_map_lefp_id'), 'tbl_user_LEFP_map', ['lefp_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_LEFP_map_updated_by'), 'tbl_user_LEFP_map', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_LEFP_map_user_id'), 'tbl_user_LEFP_map', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_user_LEFP_map_user_id'), table_name='tbl_user_LEFP_map')
    op.drop_index(op.f('ix_tbl_user_LEFP_map_updated_by'), table_name='tbl_user_LEFP_map')
    op.drop_index(op.f('ix_tbl_user_LEFP_map_lefp_id'), table_name='tbl_user_LEFP_map')
    op.drop_index(op.f('ix_tbl_user_LEFP_map_id'), table_name='tbl_user_LEFP_map')
    op.drop_index(op.f('ix_tbl_user_LEFP_map_created_by'), table_name='tbl_user_LEFP_map')
    op.drop_table('tbl_user_LEFP_map')
    op.drop_index(op.f('ix_tbl_user_legal_entity_map_user_id'), table_name='tbl_user_legal_entity_map')
    op.drop_index(op.f('ix_tbl_user_legal_entity_map_updated_by'), table_name='tbl_user_legal_entity_map')
    op.drop_index(op.f('ix_tbl_user_legal_entity_map_legal_entity_id'), table_name='tbl_user_legal_entity_map')
    op.drop_index(op.f('ix_tbl_user_legal_entity_map_id'), table_name='tbl_user_legal_entity_map')
    op.drop_index(op.f('ix_tbl_user_legal_entity_map_created_by'), table_name='tbl_user_legal_entity_map')
    op.drop_table('tbl_user_legal_entity_map')
    op.drop_index(op.f('ix_tbl_user_SFP_map_user_id'), table_name='tbl_user_SFP_map')
    op.drop_index(op.f('ix_tbl_user_SFP_map_updated_by'), table_name='tbl_user_SFP_map')
    op.drop_index(op.f('ix_tbl_user_SFP_map_sfp_id'), table_name='tbl_user_SFP_map')
    op.drop_index(op.f('ix_tbl_user_SFP_map_id'), table_name='tbl_user_SFP_map')
    op.drop_index(op.f('ix_tbl_user_SFP_map_created_by'), table_name='tbl_user_SFP_map')
    op.drop_table('tbl_user_SFP_map')
    op.drop_index(op.f('ix_tbl_LEFP_updated_by'), table_name='tbl_LEFP')
    op.drop_index(op.f('ix_tbl_LEFP_portfolio_id'), table_name='tbl_LEFP')
    op.drop_index(op.f('ix_tbl_LEFP_number'), table_name='tbl_LEFP')
    op.drop_index(op.f('ix_tbl_LEFP_legal_entity_id'), table_name='tbl_LEFP')
    op.drop_index(op.f('ix_tbl_LEFP_id'), table_name='tbl_LEFP')
    op.drop_index(op.f('ix_tbl_LEFP_created_by'), table_name='tbl_LEFP')
    op.drop_table('tbl_LEFP')
    op.drop_index(op.f('ix_tbl_user_society_map_user_id'), table_name='tbl_user_society_map')
    op.drop_index(op.f('ix_tbl_user_society_map_updated_by'), table_name='tbl_user_society_map')
    op.drop_index(op.f('ix_tbl_user_society_map_society_id'), table_name='tbl_user_society_map')
    op.drop_index(op.f('ix_tbl_user_society_map_id'), table_name='tbl_user_society_map')
    op.drop_index(op.f('ix_tbl_user_society_map_created_by'), table_name='tbl_user_society_map')
    op.drop_table('tbl_user_society_map')
    op.drop_index(op.f('ix_tbl_user_CFP_map_user_id'), table_name='tbl_user_CFP_map')
    op.drop_index(op.f('ix_tbl_user_CFP_map_updated_by'), table_name='tbl_user_CFP_map')
    op.drop_index(op.f('ix_tbl_user_CFP_map_id'), table_name='tbl_user_CFP_map')
    op.drop_index(op.f('ix_tbl_user_CFP_map_created_by'), table_name='tbl_user_CFP_map')
    op.drop_index(op.f('ix_tbl_user_CFP_map_cfp_id'), table_name='tbl_user_CFP_map')
    op.drop_table('tbl_user_CFP_map')
    op.drop_index(op.f('ix_tbl_legal_entity_updated_by'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_type'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_state_id'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_society_id'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_region_id'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_province_id'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_portfolio_id'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_place'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_name'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_id'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_financial_assistance'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_district_id'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_created_by'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_country_id'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_community_id'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_code'), table_name='tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_legal_entity_address'), table_name='tbl_legal_entity')
    op.drop_table('tbl_legal_entity')
    op.drop_index(op.f('ix_tbl_SFP_updated_by'), table_name='tbl_SFP')
    op.drop_index(op.f('ix_tbl_SFP_society_id'), table_name='tbl_SFP')
    op.drop_index(op.f('ix_tbl_SFP_portfolio_id'), table_name='tbl_SFP')
    op.drop_index(op.f('ix_tbl_SFP_number'), table_name='tbl_SFP')
    op.drop_index(op.f('ix_tbl_SFP_id'), table_name='tbl_SFP')
    op.drop_index(op.f('ix_tbl_SFP_created_by'), table_name='tbl_SFP')
    op.drop_table('tbl_SFP')
    op.drop_index(op.f('ix_tbl_user_community_map_user_id'), table_name='tbl_user_community_map')
    op.drop_index(op.f('ix_tbl_user_community_map_updated_by'), table_name='tbl_user_community_map')
    op.drop_index(op.f('ix_tbl_user_community_map_id'), table_name='tbl_user_community_map')
    op.drop_index(op.f('ix_tbl_user_community_map_created_by'), table_name='tbl_user_community_map')
    op.drop_index(op.f('ix_tbl_user_community_map_community_id'), table_name='tbl_user_community_map')
    op.drop_table('tbl_user_community_map')
    op.drop_index(op.f('ix_tbl_society_updated_by'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_state_id'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_region_id'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_province_id'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_place'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_name'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_id'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_district_id'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_created_by'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_country_id'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_community_id'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_code'), table_name='tbl_society')
    op.drop_index(op.f('ix_tbl_society_address'), table_name='tbl_society')
    op.drop_table('tbl_society')
    op.drop_index(op.f('ix_tbl_CFP_updated_by'), table_name='tbl_CFP')
    op.drop_index(op.f('ix_tbl_CFP_portfolio_id'), table_name='tbl_CFP')
    op.drop_index(op.f('ix_tbl_CFP_number'), table_name='tbl_CFP')
    op.drop_index(op.f('ix_tbl_CFP_id'), table_name='tbl_CFP')
    op.drop_index(op.f('ix_tbl_CFP_created_by'), table_name='tbl_CFP')
    op.drop_index(op.f('ix_tbl_CFP_community_id'), table_name='tbl_CFP')
    op.drop_table('tbl_CFP')
    op.drop_index(op.f('ix_tbl_portfolio_updated_by'), table_name='tbl_portfolio')
    op.drop_index(op.f('ix_tbl_portfolio_name'), table_name='tbl_portfolio')
    op.drop_index(op.f('ix_tbl_portfolio_id'), table_name='tbl_portfolio')
    op.drop_index(op.f('ix_tbl_portfolio_created_by'), table_name='tbl_portfolio')
    op.drop_table('tbl_portfolio')
    op.drop_index(op.f('ix_tbl_community_updated_by'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_state_id'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_region_id'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_province_id'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_place'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_name'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_id'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_district_id'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_created_by'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_country_id'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_code'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_address'), table_name='tbl_community')
    op.drop_index(op.f('ix_tbl_community_acme_code'), table_name='tbl_community')
    op.drop_table('tbl_community')
    # ### end Alembic commands ###
