"""portfolio_id added in community and society

Revision ID: fd7a9ffa5d77
Revises: 4f082a5e1bdd
Create Date: 2025-05-09 16:59:52.667236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7a9ffa5d77'
down_revision: Union[str, None] = '4f082a5e1bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_community', sa.Column('portfolio_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tbl_community_portfolio_id'), 'tbl_community', ['portfolio_id'], unique=False)
    op.create_foreign_key('tbl_community_portfolio_id_fkey', 'tbl_community', 'tbl_portfolio', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.add_column('tbl_society', sa.Column('portfolio_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tbl_society_portfolio_id'), 'tbl_society', ['portfolio_id'], unique=False)
    op.create_foreign_key('tbl_society_portfolio_id_fkey', 'tbl_society', 'tbl_portfolio', ['portfolio_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_society_portfolio_id_fkey', 'tbl_society', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_society_portfolio_id'), table_name='tbl_society')
    op.drop_column('tbl_society', 'portfolio_id')
    op.drop_constraint('tbl_community_portfolio_id_fkey', 'tbl_community', type_='foreignkey')
    op.drop_index(op.f('ix_tbl_community_portfolio_id'), table_name='tbl_community')
    op.drop_column('tbl_community', 'portfolio_id')
    # ### end Alembic commands ###
